### PR TITLE
Adding User Interface for Custom Keybindings

### PR DESCRIPTION
**Pull request by felipejoribeiro**
# Introduction
First of all, thank you for the great plugin!
This amazing utility has helped me a lot and I am excited to contribute and add value to it.

# Objective
The aim of this pull request is to introduce a user interface for custom keybindings.

# Implementation
- introduction of the following new global variables:
    - `claude_implement_keybinding`;
    - `claude_open_chat_keybinding`;
    - `claude_send_chat_message_keybinding`;
    - `claude_cancel_response_keybinding`;
- creation of the `SetupClaudeKeybindings` function to setup all non-buffer-specific keybindings;
- addition of new VimEnter autocmd to set the keybindings, following vim plugin guidelines;
- `Readme.md` edit to let users know about this new configuration option;

### CODE REVIEW

**Comment by pasky** [comment]
Thanks! Makes a lot of sense, but wdyt about having a consistent prefix for the variables rather than the suffix, e.g. `g:claude_map_implement` etc.? (or keybinding instead of map, I thought map is a bit more standard terminology but i'm not a vim plugin guru though)

**Comment by felipejoribeiro** [comment]
Yes! I agree. Map and prefixes are better indeed. Good call.

**Comment by pasky** [comment]
thx! the README is still using the old names though

**Comment by felipejoribeiro** [comment]
Sorry for the oversight. Done

**Comment by pasky** [comment]
Thank you!

**Comment by felipejoribeiro** [comment]
Glad to help

**Pull request merged**
